# Generated by Django 4.0.4 on 2022-06-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_task_postponed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
    ]
