# Generated by Django 4.0.4 on 2022-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_reminder_rename_start_date_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
