# Generated by Django 4.0.4 on 2022-05-31 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_task_archived_task_postponed_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 21, 19, 58, 34113, tzinfo=utc)),
        ),
    ]
