# Generated by Django 4.0.4 on 2022-05-31 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.CharField(choices=[('week_before', 'Week before'), ('2days_before', '2 days before'), ('1day_before', '1 day before'), ('3hours_before', '3 hours before'), ('1hour_before', '1 hour before'), ('30min_before', '30 minutes before'), ('15min_before', '15 minutes before')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 21, 49, 50, 872037, tzinfo=utc)),
        ),
    ]
