# Generated by Django 4.0.4 on 2022-06-01 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_start_date_alter_task_postponed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='reminder',
            field=models.CharField(choices=[('month_before', 'Month before'), ('2weeks_before', '2 weeks before'), ('1week_before', '1 week before'), ('3days_before', '3 days before'), ('1day_before', '1 day before'), ('3hours_before', '3 hours before')], default='month_before', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 19, 13, 14, 224554, tzinfo=utc)),
        ),
    ]
