# Generated by Django 4.0.4 on 2022-06-04 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_notification_event_reminder_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='postponed',
            field=models.CharField(blank=True, choices=[('1day', 'One day'), ('3days', 'Three days'), ('1week', 'One week'), ('2weeks', 'Two weeks'), ('1month', 'One month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.CharField(blank=True, choices=[('week_before', 'Week before'), ('2days_before', '2 days before'), ('1day_before', '1 day before'), ('3hours_before', '3 hours before'), ('1hour_before', '1 hour before'), ('30min_before', '30 minutes before'), ('15min_before', '15 minutes before')], max_length=20, null=True),
        ),
    ]
