# Generated by Django 4.0.4 on 2022-06-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_reminder_alter_event_start_date'),
        ('events', '0023_alter_task_postponed'),
    ]

    operations = [
    ]
