# Generated by Django 4.0.4 on 2022-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_event_reminder_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
