# Generated by Django 4.0.4 on 2022-06-06 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder',
            field=models.DurationField(choices=[(datetime.timedelta(days=-28), 'Month before'), (datetime.timedelta(days=-14), '2 weeks before'), (datetime.timedelta(days=-7), '1 week before'), (datetime.timedelta(days=-3), '3 days before'), (datetime.timedelta(days=-1), '1 day before'), (datetime.timedelta(days=-1, seconds=75600), '3 hours before'), (datetime.timedelta(days=-1, seconds=82800), '1 hour before')], default=datetime.timedelta(days=-28)),
        ),
    ]
