# Generated by Django 4.0.4 on 2022-06-13 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeatable',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(days=28), 'Monthly'), (datetime.timedelta(days=365), 'Yearly')], default=datetime.timedelta(days=28)),
        ),
    ]
