# Generated by Django 4.0.4 on 2022-06-13 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_alter_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=7200), 'Two hours'), (datetime.timedelta(seconds=10800), 'Three hours'), (datetime.timedelta(seconds=21600), 'Six hours'), (datetime.timedelta(seconds=43200), 'Twelve hours'), (datetime.timedelta(days=1), 'One day')], default=datetime.timedelta(seconds=3600)),
        ),
    ]
