# Generated by Django 4.0.4 on 2022-06-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_alter_task_postpone_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='postpone_period',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Week')], default='YEAH', max_length=20),
        ),
    ]
