# Generated by Django 4.0.4 on 2022-06-13 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_task_postpone_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='postpostponed',
            field=models.DurationField(blank=True, choices=[((datetime.timedelta(days=1), 'One day'), ((datetime.timedelta(days=7), 'One week'), (datetime.timedelta(days=21), 'Three weeks')))], default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='postpone_period',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks')], default='YEAH', max_length=20),
        ),
    ]
