# Generated by Django 4.0.4 on 2022-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_task_postpostponed_alter_task_postpone_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='postpostponed',
        ),
        migrations.AddField(
            model_name='task',
            name='postpone_number',
            field=models.FloatField(default=1),
        ),
    ]
