# Generated by Django 4.0.4 on 2022-06-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_remove_task_postpostponed_task_postpone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='postpone_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postponed',
        ),
    ]
