# Generated by Django 4.0.4 on 2022-06-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_remove_task_postpone_period_task_postponed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_at',
        ),
    ]
