# Generated by Django 4.0.4 on 2022-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_alter_task_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(null=True),
        ),
    ]
