# Generated by Django 4.0.4 on 2022-06-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_alter_task_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reminder',
            new_name='postponed_reminder',
        ),
    ]
