# Generated by Django 4.0.4 on 2022-06-15 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_rename_reminder_task_postponed_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_deadline_reminder',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
