# Generated by Django 4.0.4 on 2022-06-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_task__deadline_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='postponed_reminder',
            new_name='reminder',
        ),
        migrations.RemoveField(
            model_name='task',
            name='_deadline_reminder',
        ),
    ]
