# Generated by Django 4.0.4 on 2022-06-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_rename_postponed_reminder_task_reminder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reminder',
            new_name='postponed_reminder',
        ),
    ]
