# Generated by Django 4.0.4 on 2022-06-15 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_alter_task_postponed_alter_task_postponed_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_deadline_reminder',
        ),
        migrations.AlterField(
            model_name='task',
            name='postponed',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(days=1), 'One day'), (datetime.timedelta(days=3), 'Three days'), (datetime.timedelta(days=7), 'One week'), (datetime.timedelta(days=14), 'Two weeks'), (datetime.timedelta(days=28), 'One month')], default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='postponed_reminder',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(days=-7), 'Week before'), (datetime.timedelta(days=-2), '2 days before'), (datetime.timedelta(days=-1), '1 day before'), (datetime.timedelta(days=-1, seconds=75600), '3 hours before'), (datetime.timedelta(days=-1, seconds=82800), '1 hour before')], default=datetime.timedelta(0)),
        ),
    ]
