# Generated by Django 4.0.4 on 2022-06-15 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_remove_task__deadline_reminder_alter_task_postponed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_deadline_reminder',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
