# Generated by Django 4.0.4 on 2022-06-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_task__deadline_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_deadline_reminder',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postponed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postponed_reminder',
        ),
    ]
