# Generated by Django 4.0.4 on 2022-06-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_alter_task_postponed_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_deadline_reminder',
        ),
    ]
