# Generated by Django 4.0.4 on 2022-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_remove_task__deadline_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_deadline_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
