# Generated by Django 4.0.4 on 2022-06-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_alter_task__deadline_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_deadline_reminder',
        ),
    ]
