# Generated by Django 4.0.4 on 2022-06-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_remove_task__deadline_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='postponed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postponed_reminder',
        ),
    ]
